### ISSUE TITLE
How does semantic search work with encryption?

### ISSUE THREAD

**Issue by ElasticBottle** [VedankPurohit/LiveRecall#1]
Hey VedankPurohit,

Cool project! Love hag you're doing. Kinda curious how you're managing to perform semantic search alongside encryption?

Would love to get a high level overview and pointed in the right direction in the code!

**Comment by VedankPurohit** [comment]
It's a great question.

When an image is captured, it's embedding is created and then it's instently encrypted by the key you provide. This embedding vector is saved unencrypted hence there is no need to encrypt it's embedding 

The sementic search is performed on an index which only contained Vector of the image and image location.

Then the located images are temporarily decripted and show to you. Then the decripted image is deleted
